import type { Deck } from './types';
import { generateId } from './utils';

// Sample decks for MVP
export const sampleDecks: Deck[] = [
  {
    id: 'movies',
    name: 'Movies & TV',
    description: 'Famous films and television shows',
    icon: '🎬',
    color: 'primary',
    isPremium: false,
    words: [
      { id: generateId(), text: 'Titanic' },
      { id: generateId(), text: 'Star Wars' },
      { id: generateId(), text: 'The Matrix' },
      { id: generateId(), text: 'Friends' },
      { id: generateId(), text: 'Breaking Bad' },
      { id: generateId(), text: 'The Godfather' },
      { id: generateId(), text: 'Jurassic Park' },
      { id: generateId(), text: 'Game of Thrones' },
      { id: generateId(), text: 'Harry Potter' },
      { id: generateId(), text: 'The Office' },
      { id: generateId(), text: 'Stranger Things' },
      { id: generateId(), text: 'Forrest Gump' },
      { id: generateId(), text: 'The Avengers' },
      { id: generateId(), text: 'Inception' },
      { id: generateId(), text: 'The Lion King' },
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    description: 'Creatures from around the world',
    icon: '🦁',
    color: 'success',
    isPremium: false,
    words: [
      { id: generateId(), text: 'Elephant' },
      { id: generateId(), text: 'Penguin' },
      { id: generateId(), text: 'Giraffe' },
      { id: generateId(), text: 'Dolphin' },
      { id: generateId(), text: 'Kangaroo' },
      { id: generateId(), text: 'Octopus' },
      { id: generateId(), text: 'Butterfly' },
      { id: generateId(), text: 'Crocodile' },
      { id: generateId(), text: 'Flamingo' },
      { id: generateId(), text: 'Cheetah' },
      { id: generateId(), text: 'Koala' },
      { id: generateId(), text: 'Peacock' },
      { id: generateId(), text: 'Platypus' },
      { id: generateId(), text: 'Chameleon' },
      { id: generateId(), text: 'Hedgehog' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Games',
    description: 'Athletic activities and popular games',
    icon: '⚽',
    color: 'accent',
    isPremium: false,
    words: [
      { id: generateId(), text: 'Basketball' },
      { id: generateId(), text: 'Tennis' },
      { id: generateId(), text: 'Swimming' },
      { id: generateId(), text: 'Chess' },
      { id: generateId(), text: 'Volleyball' },
      { id: generateId(), text: 'Skateboarding' },
      { id: generateId(), text: 'Golf' },
      { id: generateId(), text: 'Marathon' },
      { id: generateId(), text: 'Archery' },
      { id: generateId(), text: 'Surfing' },
      { id: generateId(), text: 'Wrestling' },
      { id: generateId(), text: 'Poker' },
      { id: generateId(), text: 'Gymnastics' },
      { id: generateId(), text: 'Hockey' },
      { id: generateId(), text: 'Snowboarding' },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drinks',
    description: 'Delicious dishes from everywhere',
    icon: '🍕',
    color: 'warning',
    isPremium: false,
    words: [
      { id: generateId(), text: 'Spaghetti' },
      { id: generateId(), text: 'Sushi' },
      { id: generateId(), text: 'Hamburger' },
      { id: generateId(), text: 'Chocolate' },
      { id: generateId(), text: 'Croissant' },
      { id: generateId(), text: 'Tacos' },
      { id: generateId(), text: 'Ice Cream' },
      { id: generateId(), text: 'Pancakes' },
      { id: generateId(), text: 'Curry' },
      { id: generateId(), text: 'Cheesecake' },
      { id: generateId(), text: 'Ramen' },
      { id: generateId(), text: 'Burrito' },
      { id: generateId(), text: 'Waffles' },
      { id: generateId(), text: 'Lasagna' },
      { id: generateId(), text: 'Milkshake' },
    ],
  },
  {
    id: 'celebrities',
    name: 'Famous People',
    description: 'Celebrities and historical figures',
    icon: '⭐',
    color: 'secondary',
    isPremium: true,
    words: [
      { id: generateId(), text: 'Albert Einstein' },
      { id: generateId(), text: 'Taylor Swift' },
      { id: generateId(), text: 'Leonardo da Vinci' },
      { id: generateId(), text: 'Michael Jordan' },
      { id: generateId(), text: 'Beyoncé' },
      { id: generateId(), text: 'Elon Musk' },
      { id: generateId(), text: 'Cleopatra' },
      { id: generateId(), text: 'Shakespeare' },
      { id: generateId(), text: 'Oprah Winfrey' },
      { id: generateId(), text: 'Mozart' },
      { id: generateId(), text: 'Gandhi' },
      { id: generateId(), text: 'Elvis Presley' },
      { id: generateId(), text: 'Marie Curie' },
      { id: generateId(), text: 'Muhammad Ali' },
      { id: generateId(), text: 'Steve Jobs' },
    ],
  },
  {
    id: 'actions',
    name: 'Actions & Verbs',
    description: 'Things people do - act them out!',
    icon: '🏃',
    color: 'destructive',
    isPremium: true,
    words: [
      { id: generateId(), text: 'Dancing' },
      { id: generateId(), text: 'Sleeping' },
      { id: generateId(), text: 'Cooking' },
      { id: generateId(), text: 'Laughing' },
      { id: generateId(), text: 'Swimming' },
      { id: generateId(), text: 'Flying' },
      { id: generateId(), text: 'Singing' },
      { id: generateId(), text: 'Painting' },
      { id: generateId(), text: 'Running' },
      { id: generateId(), text: 'Thinking' },
      { id: generateId(), text: 'Dreaming' },
      { id: generateId(), text: 'Fighting' },
      { id: generateId(), text: 'Climbing' },
      { id: generateId(), text: 'Shopping' },
      { id: generateId(), text: 'Studying' },
    ],
  },
];

export function getDeckById(id: string): Deck | undefined {
  return sampleDecks.find(deck => deck.id === id);
}

export function getFreeDeck(): Deck[] {
  return sampleDecks.filter(deck => !deck.isPremium);
}

export function getPremiumDecks(): Deck[] {
  return sampleDecks.filter(deck => deck.isPremium);
}
