import type { Deck } from './types';
import { generateId } from './utils';

export const sampleDecks: Deck[] = [
  {
    id: 'movies',
    name: 'Filmy i seriale',
    description: 'Znane filmy i seriale telewizyjne',
    icon: '🎬',
    image: require('../../assets/decks/movies_seasons.png'),
    color: '#4F46E5',
    isPremium: false,
    difficulty: 'easy',
    words: [
      { id: generateId(), text: 'Avatar' },
      { id: generateId(), text: 'Titanic' },
      { id: generateId(), text: 'Ojciec chrzestny' },
      { id: generateId(), text: 'Pulp Fiction' },
      { id: generateId(), text: 'Forrest Gump' },
      { id: generateId(), text: 'Mroczny Rycerz' },
      { id: generateId(), text: 'Park Jurajski' },
      { id: generateId(), text: 'Szczęki' },
      { id: generateId(), text: 'Rocky' },
      { id: generateId(), text: 'Rambo' },
      { id: generateId(), text: 'Terminator' },
      { id: generateId(), text: 'Powrót do przyszłości' },
      { id: generateId(), text: 'Indiana Jones' },
      { id: generateId(), text: 'Szklana pułapka' },
      { id: generateId(), text: 'Gladiator' },
      { id: generateId(), text: 'Braveheart' },
      { id: generateId(), text: 'Szeregowiec Ryan' },
      { id: generateId(), text: 'Incepcja' },
      { id: generateId(), text: 'Interstellar' },
      { id: generateId(), text: 'Podziemny krąg' },
      { id: generateId(), text: 'Gwiezdne Wojny' },
      { id: generateId(), text: 'Harry Potter' },
      { id: generateId(), text: 'Władca Pierścieni' },
      { id: generateId(), text: 'Matrix' },
      { id: generateId(), text: 'Avengers' },
      { id: generateId(), text: 'Iron Man' },
      { id: generateId(), text: 'Spider-Man' },
      { id: generateId(), text: 'Batman' },
      { id: generateId(), text: 'Superman' },
      { id: generateId(), text: 'Transformers' },
      { id: generateId(), text: 'Piraci z Karaibów' },
      { id: generateId(), text: 'Kevin sam w domu' },
      { id: generateId(), text: 'Kac Vegas' },
      { id: generateId(), text: 'Pan Bean' },
      { id: generateId(), text: 'Shrek' },
      { id: generateId(), text: 'Toy Story' },
      { id: generateId(), text: 'Gdzie jest Nemo' },
      { id: generateId(), text: 'Epoka lodowcowa' },
      { id: generateId(), text: 'Kung Fu Panda' },
      { id: generateId(), text: 'Madagaskar' },
      { id: generateId(), text: 'Przyjaciele' },
      { id: generateId(), text: 'The Office' },
      { id: generateId(), text: 'Breaking Bad' },
      { id: generateId(), text: 'Gra o Tron' },
      { id: generateId(), text: 'Stranger Things' },
      { id: generateId(), text: 'Simpsonowie' },
      { id: generateId(), text: 'Jak poznałem waszą matkę' },
      { id: generateId(), text: 'Teoria Wielkiego Podrywu' },
      { id: generateId(), text: 'Narcos' },
      { id: generateId(), text: 'Dom z papieru' },
      { id: generateId(), text: 'Squid Game' },
      { id: generateId(), text: 'Żywe trupy' },
      { id: generateId(), text: 'Zagubieni' },
      { id: generateId(), text: 'Król Lew' },
      { id: generateId(), text: 'Kraina Lodu' },
      { id: generateId(), text: 'Aladyn' },
      { id: generateId(), text: 'Piękna i Bestia' },
      { id: generateId(), text: 'Mulan' },
      { id: generateId(), text: 'Coco' },
      { id: generateId(), text: 'Odlot' },
    ],
  },
  {
    id: 'animals',
    name: 'Zwierzęta',
    description: 'Stworzenia z całego świata',
    icon: '🦁',
    image: require('../../assets/decks/animals.png'),
    color: '#10B981',
    isPremium: false,
    difficulty: 'easy',
    words: [
      { id: generateId(), text: 'Słoń' },
      { id: generateId(), text: 'Pingwin' },
      { id: generateId(), text: 'Żyrafa' },
      { id: generateId(), text: 'Delfin' },
      { id: generateId(), text: 'Kangur' },
      { id: generateId(), text: 'Ośmiornica' },
      { id: generateId(), text: 'Motyl' },
      { id: generateId(), text: 'Krokodyl' },
      { id: generateId(), text: 'Flaming' },
      { id: generateId(), text: 'Gepard' },
      { id: generateId(), text: 'Koala' },
      { id: generateId(), text: 'Paw' },
      { id: generateId(), text: 'Dziobak' },
      { id: generateId(), text: 'Kameleon' },
      { id: generateId(), text: 'Jeż' },
    ],
  },
  {
    id: 'sports',
    name: 'Sport i gry',
    description: 'Aktywności sportowe i popularne gry',
    icon: '⚽',
    image: require('../../assets/decks/sports_games.png'),
    color: '#F59E0B',
    isPremium: false,
    difficulty: 'medium',
    words: [
      { id: generateId(), text: 'Koszykówka' },
      { id: generateId(), text: 'Tenis' },
      { id: generateId(), text: 'Pływanie' },
      { id: generateId(), text: 'Szachy' },
      { id: generateId(), text: 'Siatkówka' },
      { id: generateId(), text: 'Skateboarding' },
      { id: generateId(), text: 'Golf' },
      { id: generateId(), text: 'Maraton' },
      { id: generateId(), text: 'Łucznictwo' },
      { id: generateId(), text: 'Surfing' },
      { id: generateId(), text: 'Zapasy' },
      { id: generateId(), text: 'Poker' },
      { id: generateId(), text: 'Gimnastyka' },
      { id: generateId(), text: 'Hokej' },
      { id: generateId(), text: 'Snowboard' },
    ],
  },
  {
    id: 'food',
    name: 'Jedzenie i napoje',
    description: 'Pyszne dania z całego świata',
    icon: '🍕',
    image: require('../../assets/decks/food_drinks.png'),
    color: '#EF4444',
    isPremium: false,
    difficulty: 'easy',
    words: [
      { id: generateId(), text: 'Spaghetti' },
      { id: generateId(), text: 'Sushi' },
      { id: generateId(), text: 'Hamburger' },
      { id: generateId(), text: 'Czekolada' },
      { id: generateId(), text: 'Croissant' },
      { id: generateId(), text: 'Tacos' },
      { id: generateId(), text: 'Lody' },
      { id: generateId(), text: 'Naleśniki' },
      { id: generateId(), text: 'Curry' },
      { id: generateId(), text: 'Sernik' },
      { id: generateId(), text: 'Ramen' },
      { id: generateId(), text: 'Burrito' },
      { id: generateId(), text: 'Gofry' },
      { id: generateId(), text: 'Lazania' },
      { id: generateId(), text: 'Koktajl mleczny' },
    ],
  },
  {
    id: 'celebrities',
    name: 'Znane osoby',
    description: 'Celebryci i postaci historyczne',
    icon: '⭐',
    image: require('../../assets/decks/famous_people.png'),
    color: '#8B5CF6',
    isPremium: true,
    difficulty: 'medium',
    words: [
      { id: generateId(), text: 'Albert Einstein' },
      { id: generateId(), text: 'Taylor Swift' },
      { id: generateId(), text: 'Leonardo da Vinci' },
      { id: generateId(), text: 'Michael Jordan' },
      { id: generateId(), text: 'Beyoncé' },
      { id: generateId(), text: 'Elon Musk' },
      { id: generateId(), text: 'Kleopatra' },
      { id: generateId(), text: 'Shakespeare' },
      { id: generateId(), text: 'Oprah Winfrey' },
      { id: generateId(), text: 'Mozart' },
      { id: generateId(), text: 'Gandhi' },
      { id: generateId(), text: 'Elvis Presley' },
      { id: generateId(), text: 'Maria Curie' },
      { id: generateId(), text: 'Muhammad Ali' },
      { id: generateId(), text: 'Steve Jobs' },
      { id: generateId(), text: 'Napoleon Bonaparte' },
      { id: generateId(), text: 'Juliusz Cezar' },
      { id: generateId(), text: 'Abraham Lincoln' },
      { id: generateId(), text: 'Winston Churchill' },
      { id: generateId(), text: 'Nelson Mandela' },
      { id: generateId(), text: 'Aleksander Wielki' },
      { id: generateId(), text: 'Czyngis-chan' },
      { id: generateId(), text: 'Isaac Newton' },
      { id: generateId(), text: 'Karol Darwin' },
      { id: generateId(), text: 'Nikola Tesla' },
      { id: generateId(), text: 'Galileusz' },
      { id: generateId(), text: 'Stephen Hawking' },
      { id: generateId(), text: 'Tomasz Edison' },
      { id: generateId(), text: 'Alan Turing' },
      { id: generateId(), text: 'Vincent van Gogh' },
      { id: generateId(), text: 'Pablo Picasso' },
      { id: generateId(), text: 'Michał Anioł' },
      { id: generateId(), text: 'Michael Jackson' },
      { id: generateId(), text: 'Madonna' },
      { id: generateId(), text: 'Rihanna' },
      { id: generateId(), text: 'Lady Gaga' },
      { id: generateId(), text: 'Brad Pitt' },
      { id: generateId(), text: 'Leonardo DiCaprio' },
      { id: generateId(), text: 'Marilyn Monroe' },
      { id: generateId(), text: 'Charlie Chaplin' },
      { id: generateId(), text: 'Pelé' },
      { id: generateId(), text: 'Cristiano Ronaldo' },
      { id: generateId(), text: 'Lionel Messi' },
      { id: generateId(), text: 'Usain Bolt' },
      { id: generateId(), text: 'Serena Williams' },
      { id: generateId(), text: 'Roger Federer' },
      { id: generateId(), text: 'Mike Tyson' },
      { id: generateId(), text: 'LeBron James' },
      { id: generateId(), text: 'Bill Gates' },
      { id: generateId(), text: 'Mark Zuckerberg' },
      { id: generateId(), text: 'Jeff Bezos' },
    ],
  },
  {
    id: 'actions',
    name: 'Czynności i gesty',
    description: 'Co robią ludzie — odgadnij lub pokaż!',
    icon: '🏃',
    image: require('../../assets/decks/actions_gestures.png'),
    color: '#EC4899',
    isPremium: true,
    difficulty: 'hard',
    words: [
      { id: generateId(), text: 'Taniec' },
      { id: generateId(), text: 'Spanie' },
      { id: generateId(), text: 'Gotowanie' },
      { id: generateId(), text: 'Śmiech' },
      { id: generateId(), text: 'Pływanie' },
      { id: generateId(), text: 'Latanie' },
      { id: generateId(), text: 'Śpiewanie' },
      { id: generateId(), text: 'Malowanie' },
      { id: generateId(), text: 'Bieganie' },
      { id: generateId(), text: 'Myślenie' },
      { id: generateId(), text: 'Marzenie' },
      { id: generateId(), text: 'Walka' },
      { id: generateId(), text: 'Wspinaczka' },
      { id: generateId(), text: 'Zakupy' },
      { id: generateId(), text: 'Nauka' },
    ],
  },
];

export function getDeckById(id: string): Deck | undefined {
  return sampleDecks.find(deck => deck.id === id);
}

export function getFreeDecks(): Deck[] {
  return sampleDecks.filter(deck => !deck.isPremium);
}

export function getPremiumDecks(): Deck[] {
  return sampleDecks.filter(deck => deck.isPremium);
}
