import type { Deck } from './types';
import { generateId } from './utils';

// Sample decks for MVP
export const sampleDecks: Deck[] = [
  {
    id: 'movies',
    name: 'Movies & TV',
    description: 'Famous films and television shows',
    icon: '🎬',
    color: 'primary',
    isPremium: false,
    difficulty: 'easy',
    words: [
      // Classic movies and hits
      { id: generateId(), text: 'Avatar' },
      { id: generateId(), text: 'Titanic' },
      { id: generateId(), text: 'The Godfather' },
      { id: generateId(), text: 'Pulp Fiction' },
      { id: generateId(), text: 'Forrest Gump' },
      { id: generateId(), text: 'The Dark Knight' },
      { id: generateId(), text: 'Jurassic Park' },
      { id: generateId(), text: 'Jaws' },
      { id: generateId(), text: 'Rocky' },
      { id: generateId(), text: 'Rambo' },
      { id: generateId(), text: 'Terminator' },
      { id: generateId(), text: 'Back to the Future' },
      { id: generateId(), text: 'Indiana Jones' },
      { id: generateId(), text: 'Die Hard' },
      { id: generateId(), text: 'Gladiator' },
      { id: generateId(), text: 'Braveheart' },
      { id: generateId(), text: 'Saving Private Ryan' },
      { id: generateId(), text: 'Inception' },
      { id: generateId(), text: 'Interstellar' },
      { id: generateId(), text: 'Fight Club' },
      // Sci-fi and fantasy
      { id: generateId(), text: 'Star Wars' },
      { id: generateId(), text: 'Harry Potter' },
      { id: generateId(), text: 'The Lord of the Rings' },
      { id: generateId(), text: 'The Matrix' },
      { id: generateId(), text: 'The Avengers' },
      { id: generateId(), text: 'Iron Man' },
      { id: generateId(), text: 'Spider-Man' },
      { id: generateId(), text: 'Batman' },
      { id: generateId(), text: 'Superman' },
      { id: generateId(), text: 'Transformers' },
      { id: generateId(), text: 'Pirates of the Caribbean' },
      // Comedy and family hits
      { id: generateId(), text: 'Home Alone' },
      { id: generateId(), text: 'The Hangover' },
      { id: generateId(), text: 'Mr. Bean' },
      { id: generateId(), text: 'Charlie and the Chocolate Factory' },
      { id: generateId(), text: 'Shrek' },
      { id: generateId(), text: 'Toy Story' },
      { id: generateId(), text: 'Finding Nemo' },
      { id: generateId(), text: 'Ice Age' },
      { id: generateId(), text: 'Kung Fu Panda' },
      { id: generateId(), text: 'Madagascar' },
      // Popular TV shows
      { id: generateId(), text: 'Friends' },
      { id: generateId(), text: 'The Office' },
      { id: generateId(), text: 'Breaking Bad' },
      { id: generateId(), text: 'Game of Thrones' },
      { id: generateId(), text: 'Stranger Things' },
      { id: generateId(), text: 'The Simpsons' },
      { id: generateId(), text: 'How I Met Your Mother' },
      { id: generateId(), text: 'Big Bang Theory' },
      { id: generateId(), text: 'House of Cards' },
      { id: generateId(), text: 'Narcos' },
      { id: generateId(), text: 'Money Heist' },
      { id: generateId(), text: 'Squid Game' },
      { id: generateId(), text: 'The Walking Dead' },
      { id: generateId(), text: 'Lost' },
      { id: generateId(), text: 'Dexter' },
      // Animated movies
      { id: generateId(), text: 'The Lion King' },
      { id: generateId(), text: 'Frozen' },
      { id: generateId(), text: 'Aladdin' },
      { id: generateId(), text: 'Beauty and the Beast' },
      { id: generateId(), text: 'Mulan' },
      { id: generateId(), text: 'Coco' },
      { id: generateId(), text: 'Up' },
      { id: generateId(), text: 'Cars' },
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    description: 'Creatures from around the world',
    icon: '🦁',
    color: 'success',
    isPremium: false,
    difficulty: 'easy',
    words: [
      { id: generateId(), text: 'Elephant' },
      { id: generateId(), text: 'Penguin' },
      { id: generateId(), text: 'Giraffe' },
      { id: generateId(), text: 'Dolphin' },
      { id: generateId(), text: 'Kangaroo' },
      { id: generateId(), text: 'Octopus' },
      { id: generateId(), text: 'Butterfly' },
      { id: generateId(), text: 'Crocodile' },
      { id: generateId(), text: 'Flamingo' },
      { id: generateId(), text: 'Cheetah' },
      { id: generateId(), text: 'Koala' },
      { id: generateId(), text: 'Peacock' },
      { id: generateId(), text: 'Platypus' },
      { id: generateId(), text: 'Chameleon' },
      { id: generateId(), text: 'Hedgehog' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports & Games',
    description: 'Athletic activities and popular games',
    icon: '⚽',
    color: 'accent',
    isPremium: false,
    difficulty: 'medium',
    words: [
      { id: generateId(), text: 'Basketball' },
      { id: generateId(), text: 'Tennis' },
      { id: generateId(), text: 'Swimming' },
      { id: generateId(), text: 'Chess' },
      { id: generateId(), text: 'Volleyball' },
      { id: generateId(), text: 'Skateboarding' },
      { id: generateId(), text: 'Golf' },
      { id: generateId(), text: 'Marathon' },
      { id: generateId(), text: 'Archery' },
      { id: generateId(), text: 'Surfing' },
      { id: generateId(), text: 'Wrestling' },
      { id: generateId(), text: 'Poker' },
      { id: generateId(), text: 'Gymnastics' },
      { id: generateId(), text: 'Hockey' },
      { id: generateId(), text: 'Snowboarding' },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drinks',
    description: 'Delicious dishes from everywhere',
    icon: '🍕',
    color: 'warning',
    isPremium: false,
    difficulty: 'easy',
    words: [
      { id: generateId(), text: 'Spaghetti' },
      { id: generateId(), text: 'Sushi' },
      { id: generateId(), text: 'Hamburger' },
      { id: generateId(), text: 'Chocolate' },
      { id: generateId(), text: 'Croissant' },
      { id: generateId(), text: 'Tacos' },
      { id: generateId(), text: 'Ice Cream' },
      { id: generateId(), text: 'Pancakes' },
      { id: generateId(), text: 'Curry' },
      { id: generateId(), text: 'Cheesecake' },
      { id: generateId(), text: 'Ramen' },
      { id: generateId(), text: 'Burrito' },
      { id: generateId(), text: 'Waffles' },
      { id: generateId(), text: 'Lasagna' },
      { id: generateId(), text: 'Milkshake' },
    ],
  },
  {
    id: 'celebrities',
    name: 'Famous People',
    description: 'Celebrities and historical figures',
    icon: '⭐',
    color: 'secondary',
    isPremium: true,
    difficulty: 'medium',
    words: [
      // First sorted by category for easier editing
      { id: generateId(), text: 'Albert Einstein' },
      { id: generateId(), text: 'Taylor Swift' },
      { id: generateId(), text: 'Leonardo da Vinci' },
      { id: generateId(), text: 'Michael Jordan' },
      { id: generateId(), text: 'Beyoncé' },
      { id: generateId(), text: 'Elon Musk' },
      { id: generateId(), text: 'Cleopatra' },
      { id: generateId(), text: 'Shakespeare' },
      { id: generateId(), text: 'Oprah Winfrey' },
      { id: generateId(), text: 'Mozart' },
      { id: generateId(), text: 'Gandhi' },
      { id: generateId(), text: 'Elvis Presley' },
      { id: generateId(), text: 'Marie Curie' },
      { id: generateId(), text: 'Muhammad Ali' },
      { id: generateId(), text: 'Steve Jobs' },
      { id: generateId(), text: 'Napoleon Bonaparte' },
      // historical and political leaders
      { id: generateId(), text: 'Julius Caesar' },
      { id: generateId(), text: 'Abraham Lincoln' },
      { id: generateId(), text: 'George Washington' },
      { id: generateId(), text: 'Winston Churchill' },
      { id: generateId(), text: 'Adolf Hitler' },
      { id: generateId(), text: 'Joseph Stalin' },
      { id: generateId(), text: 'Vladimir Lenin' },
      { id: generateId(), text: 'Nelson Mandela' },
      { id: generateId(), text: 'Margaret Thatcher' },
      { id: generateId(), text: 'Queen Elizabeth II' },
      { id: generateId(), text: 'Alexander the Great' },
      { id: generateId(), text: 'Genghis Khan' },
      { id: generateId(), text: 'Mao Zedong' },
      { id: generateId(), text: 'Fidel Castro' },
      { id: generateId(), text: 'Barack Obama' },
      { id: generateId(), text: 'Donald Trump' },
      { id: generateId(), text: 'John F. Kennedy' },
      // scientists and inventors
      { id: generateId(), text: 'Isaac Newton' },
      { id: generateId(), text: 'Charles Darwin' },
      { id: generateId(), text: 'Nikola Tesla' },
      { id: generateId(), text: 'Galileo Galilei' },
      { id: generateId(), text: 'Stephen Hawking' },
      { id: generateId(), text: 'Thomas Edison' },
      { id: generateId(), text: 'Alexander Graham Bell' },
      { id: generateId(), text: 'Louis Pasteur' },
      { id: generateId(), text: 'Sigmund Freud' },
      { id: generateId(), text: 'Alan Turing' },
      // artists and writers
      { id: generateId(), text: 'Vincent van Gogh' },
      { id: generateId(), text: 'Pablo Picasso' },
      { id: generateId(), text: 'Michelangelo' },
      { id: generateId(), text: 'Rembrandt' },
      { id: generateId(), text: 'Johann Sebastian Bach' },
      { id: generateId(), text: 'Ludwig van Beethoven' },
      { id: generateId(), text: 'Frédéric Chopin' },
      { id: generateId(), text: 'Homer' },
      { id: generateId(), text: 'Dante Alighieri' },
      { id: generateId(), text: 'Leo Tolstoy' },
      { id: generateId(), text: 'Michael Jackson' },
      // pop culture icons
      { id: generateId(), text: 'Madonna' },
      { id: generateId(), text: 'The Beatles' },
      { id: generateId(), text: 'Bob Dylan' },
      { id: generateId(), text: 'Rihanna' },
      { id: generateId(), text: 'Drake' },
      { id: generateId(), text: 'Lady Gaga' },
      { id: generateId(), text: 'Brad Pitt' },
      { id: generateId(), text: 'Leonardo DiCaprio' },
      { id: generateId(), text: 'Marilyn Monroe' },
      { id: generateId(), text: 'Charlie Chaplin' },
      { id: generateId(), text: 'Tom Cruise' },
      { id: generateId(), text: 'Arnold Schwarzenegger' },
      { id: generateId(), text: 'Jennifer Lawrence' },
      { id: generateId(), text: 'Scarlett Johansson' },
      // athletes
      { id: generateId(), text: 'Pelé' },
      { id: generateId(), text: 'Cristiano Ronaldo' },
      { id: generateId(), text: 'Lionel Messi' },
      { id: generateId(), text: 'Diego Maradona' },
      { id: generateId(), text: 'Usain Bolt' },
      { id: generateId(), text: 'Serena Williams' },
      { id: generateId(), text: 'Roger Federer' },
      { id: generateId(), text: 'Mike Tyson' },
      { id: generateId(), text: 'LeBron James' },
      { id: generateId(), text: 'Kobe Bryant' },
      // entrepreneurs
      { id: generateId(), text: 'Bill Gates' },
      { id: generateId(), text: 'Mark Zuckerberg' },
      { id: generateId(), text: 'Jeff Bezos' },
      { id: generateId(), text: 'Warren Buffett' },
    ],
  },
  {
    id: 'actions',
    name: 'Actions & Verbs',
    description: 'Things people do - act them out!',
    icon: '🏃',
    color: 'destructive',
    isPremium: true,
    difficulty: 'hard',
    words: [
      { id: generateId(), text: 'Dancing' },
      { id: generateId(), text: 'Sleeping' },
      { id: generateId(), text: 'Cooking' },
      { id: generateId(), text: 'Laughing' },
      { id: generateId(), text: 'Swimming' },
      { id: generateId(), text: 'Flying' },
      { id: generateId(), text: 'Singing' },
      { id: generateId(), text: 'Painting' },
      { id: generateId(), text: 'Running' },
      { id: generateId(), text: 'Thinking' },
      { id: generateId(), text: 'Dreaming' },
      { id: generateId(), text: 'Fighting' },
      { id: generateId(), text: 'Climbing' },
      { id: generateId(), text: 'Shopping' },
      { id: generateId(), text: 'Studying' },
    ],
  },
];

export function getDeckById(id: string): Deck | undefined {
  return sampleDecks.find(deck => deck.id === id);
}

export function getFreeDeck(): Deck[] {
  return sampleDecks.filter(deck => !deck.isPremium);
}

export function getPremiumDecks(): Deck[] {
  return sampleDecks.filter(deck => deck.isPremium);
}
